### ISSUE TITLE
Support setting advanced input device settings

### ISSUE THREAD

**Issue by bj00rn** [Nailik/rhasspy_mobile#326] opened 2023-04-08 15:47 UTC
This looks really promising! Nice work!

It would be nice to be able to set channel and sample rate. I have a device (rooted lenovo smart clock 2) which seems to only produce proper recordings using CHANNEL_IN_STEREO and samplerate 48kHz. CHANNEL_IN_DEFAULT is broken for all samplerates :-(

It would be nice to be able to specify settings for input somewhere in the GUI. 

Cheers!

**Comment by Nailik** [comment] 2023-04-08 16:02
Sounds reasonable.
It could be that rhasspy can't deal with another audio format. I have to try that first and if rhasspy can't deal with it the app needs to convert the audio

**Comment by mbuett** [comment] 2023-04-08 20:54
To give this some additional context:

This issue originates from [this XDA thread](https://forum.xda-developers.com/t/lets-get-started-on-the-lenovo-smart-clock-2.4374455) starting roughly with [this comment](https://forum.xda-developers.com/t/lets-get-started-on-the-lenovo-smart-clock-2.4374455/post-88385937).
The device in question (Lenovo Smart Clock 2) is (at least imho) a great satellite that doesn't require much setup thanks to your awesome app. Prior to rooting it worked more or less flawless apart from the Google/OEM stuff preventing Rhasspy Mobile from reliably running in the background.
Said OEM/Google stuff must have been responsible for making the microphone usable for other apps. After removal only apps that could be set to record using the values mentioned by @bj00rn seem to produce usable recordings.

I'm currently trying different settings. In case I get this to work (and if it is of interest) I can create a PR of the required changes. Ofc if someone is faster than me I'd also happily test their changes on one of my devices :)

Cheers :)

**Comment by Nailik** [comment] 2023-04-27 15:15
You can test if your issue is resolved with the latest dev build from the Pipline.
Feel free to reopen the issue if it still doesn't work.

**Closed** 2023-04-27 16:36 UTC
Labels: enhancement

**Comment by mbuett** [comment] 2023-05-04 22:34
Sorry for the late reply. I managed to mess up both devices and first had to set them up again.

Recording now works and the recorded audio is at least as good as before. After trying different combinations I settled for Stereo@44.1kHz and 16Bit although only Stereo seems to be required to make it work reliably. Thank you for tackling this issue super fast :) The clock can now be used as a satellite just as I had hoped! :)

There is only one thing that seems to be defective in the debug build I tried: The local wake word detection stopped working. It only displays the error symbol above the wake word settings without any additional details. I couldn't gather too much information from the log messages either.
I'll spend some more time tinkering with the device in the next days. If this is something new/unknown I can record and upload said logs.

Regardless, thanks again for the awesome app :)

**Comment by Nailik** [comment] 2023-05-08 20:28
@mbuett please file an issue for the wake word detection and state which wake word detection you were using.

**Comment by bj00rn** [comment] 2023-05-23 12:43
@Nailik i think the menu caption is wrong once it has been opened. Small issue though

**Comment by Nailik** [comment] 2023-05-23 16:52
> @Nailik i think the menu caption is wrong once it has been opened. Small issue though

thanks i'll fix this

**Comment by bj00rn** [comment] 2023-05-31 11:58
> @mbuett ~please file an issue for the wake word detection and state which wake word detection you were using.~
> 
> Your issue is probably related to #351 , simply i forgot to update the model and keyword files.

I can confirm audio recording is working fine on this device now that stereo channel is available.

But I can't seem to get porcupine local wakeword working though. Any pointers here? Im using latest nightly build.

**Comment by Nailik** [comment] 2023-05-31 17:19
those input settings are not used for porcupine and i think that's the problem here because porcupine internally uses it's own input settings.
I think there is a way to send recording data to the porcupine library instead of relying on it to correctly record the audio.

**Comment by bj00rn** [comment] 2023-05-31 20:02
I can confirm audio recording is now working on the device 

> those input settings are not used for porcupine and i think that's the problem here because porcupine internally uses it's own input settings. I think there is a way to send recording data to the porcupine library instead of relying on it to correctly record the audio.


Ah i see, In here you mean?

https://github.com/Picovoice/porcupine/blob/ec787ddcd69e54d6a54158125f0da5a4724e37d6/binding/android/Porcupine/porcupine/src/main/java/ai/picovoice/porcupine/PorcupineManager.java#L222

**Comment by Nailik** [comment] 2023-06-01 05:41
Exactly but they have this function to process incoming data 
https://github.com/Picovoice/porcupine/blob/ec787ddcd69e54d6a54158125f0da5a4724e37d6/binding/android/Porcupine/porcupine/src/main/java/ai/picovoice/porcupine/Porcupine.java#L98

The only issue is, that it seems like they only support mono pcm audio with a special sample rate so it might be required to to record the audio and then process it depending on what the user has selected in the audio settings.

**Comment by Nailik** [comment] 2023-07-24 15:52
@bj00rn could you confirm if it works when using audio recorder settings?

**Comment by bj00rn** [comment] 2023-07-27 21:17
> @bj00rn could you confirm if it works when using audio recorder settings?

Will try tomorrow!

**Comment by bj00rn** [comment] 2023-07-28 08:14
Looks like it's finslly working! Wake word is registering and triggering recording. Thank you for your effort!!!

Had to clear app data to get the app to start when installing. Will do some more testing once i get it set up again.

**Comment by bj00rn** [comment] 2023-07-28 10:48
Hmm, seems audio recording (or playback is broken now).. Pressing "play recording"

Also I think porcupine wakeword stops working after a while.

Will test some more

**Comment by bj00rn** [comment] 2023-07-28 11:12
Attaching a log file from when trying to record and playback manually
[logfile.json.zip](https://github.com/Nailik/rhasspy_mobile/files/12193860/logfile.json.zip)

**Comment by Nailik** [comment] 2023-07-28 11:16
@bj00rn mostly of the log is filled with ` StrictMode policy violation: android.os.strictmode.LeakedClosableViolation: A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks. ` which is caused by https://github.com/square/okio/issues/1228 
Maybe i can fix it by using https://github.com/Kotlin/kotlinx-io (maybe they have fixed it somehow)

**Comment by Nailik** [comment] 2023-07-28 11:18
could you also the log from the app?

**Comment by bj00rn** [comment] 2023-07-28 11:23
> could you also the log from the app?

App crashes when i try to save the log unfortunately. #400

**Comment by bj00rn** [comment] 2023-07-28 11:30
Here is a screenshot of log screen. This is the only error being logged when recording manually and pressing play recording

<img width="481" alt="image" src="https://github.com/Nailik/rhasspy_mobile/assets/10961167/62492f8b-be6a-47d0-994b-b05377db3cf3">
