### ISSUE TITLE
Saving logfile crashes app

### ISSUE THREAD

**Issue by bj00rn** [Nailik/rhasspy_mobile#400] opened 2023-07-28 11:13 UTC
Clicking save (floppydisk icon) and saving crashes app

**Comment by Nailik** [comment] 2023-07-28 11:43
could you please enable crashlytics and then provoke the crash? i can't reproduce it.

**Comment by bj00rn** [comment] 2023-07-28 11:56
> could you please enable crashlytics and then provoke the crash? i can't reproduce it.

How do i enable crashlytics?

**Comment by Nailik** [comment] 2023-07-28 12:18
In Settings Tab -> Log Settings -> Crashlytics. But i think currently it is force disabled for debug :/

**Comment by bj00rn** [comment] 2023-07-28 18:05
> In Settings Tab -> Log Settings -> Crashlytics. But i think currently it is force disabled for debug :/

I set the loglevel to info, enabled crashlytics and crashed the app again by saving logfile.

**Comment by Nailik** [comment] 2023-07-28 19:20
`But i think currently it is force disabled for debug` i meant even if you enable it, it wont send data to crashlytics because i had a issue with my tests sending events and therefore disabled it for debug.

Is there any chance there is no file app on the device? like can you select files e.g. custom porcupine wake word files or mqtt/webserver certificate files (just check if a file selection app opens).

Also please tell me what android version you use.

**Comment by bj00rn** [comment] 2023-07-28 22:01
> `But i think currently it is force disabled for debug` i meant even if you enable it, it wont send data to crashlytics because i had a issue with my tests sending events and therefore disabled it for debug.

Aahh, makes sense now 🙉 

> Is there any chance there is no file app on the device? like can you select files e.g. custom porcupine wake word files or mqtt/webserver certificate files (just check if a file selection app opens).

I tried invoking select mqtt certificate and it properly brings up the file app

> Also please tell me what android version you use.

Android 10

**Comment by Nailik** [comment] 2023-07-29 16:43
probably it crashed because log file was not correctly created will be fixed with https://github.com/Nailik/rhasspy_mobile/issues/370 

reopen if issue still exist afterwards

**Closed by Nailik** 2023-07-29 16:43 UTC
Labels: bug

**Comment by bj00rn** [comment] 2023-07-30 13:24
> probably it crashed because log file was not correctly created will be fixed with #370
> 
> reopen if issue still exist afterwards

Ok, tell me when there is a new build to test

**Comment by bj00rn** [comment] 2023-07-31 08:32
> probably it crashed because log file was not correctly created will be fixed with #370
> 
> reopen if issue still exist afterwards

Great! Working now as of 9d3a0db
